server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boulevard
    username: root
    password: Pr@gm4

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: boulevard_microservice


user_microservice:
  name: "user-microservice"
  url: "http://localhost:8082"

appDescription: "Pragma boulevard"
appVersion: "1.0.0"
